// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggplcwpyotqtuftzfgqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncGxjd3B5b3RxdHVmdHpmZ3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDQzNjcsImV4cCI6MjA2MTY4MDM2N30.3ffWuGe4or7A2fhdYjjhdidkTVTzAKhnA8WfoxzNYQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);